export const mockCharacterData = [
  {
    name: "Arthur Weasley",
    house: "Gryffindor",
    _id: 41,
  },
  {
    name: "Victoire Weasley",
    house: "Ravenclaw",
    _id: 3,
  },
  {
    name: "Albus Potter",
    house: "Slytherin",
    _id: 5,
  },
  {
    name: "Teddy Lupin",
    house: "Hufflepuff",
    _id: 28,
  },
  {
    name: "Garrick Ollivander",
    house: "Ravenclaw",
    _id: 61,
  },
]

export const mockHouseData = [
  {
    _id: 1,
    color1: "Green",
    color2: "Any other color",
    founder: "Alastor Moody",
    headOfHouse: "Rubeus Hagrid",
    houseGhost: "Hufflepuff",
    mascot: "Chameleon",
    name: "Chameleon",
    value1: "Cocky",
    value2: "Wreckless",
    value3: "Attention-seeking",
    value4: "Self-righteous",
  },
  {
    _id: 2,
    color1: "Green",
    color2: "Any other color",
    founder: "New Scamander",
    headOfHouse: "Olympe Maxime",
    houseGhost: "Hufflepuff",
    mascot: "Chameleon",
    name: "Chameleon",
    value1: "Boring",
    value2: "Unimpressive",
    value3: "Nice...",
    value4: "Dim",
  },
  {
    _id: 3,
    color1: "Green",
    color2: "Any other color",
    founder: "Vodemort",
    headOfHouse: "Firenze",
    houseGhost: "Hufflepuff",
    mascot: "Chameleon",
    name: "Chameleon",
    value1: "Entitled",
    value2: "Elitist",
    value3: "Snobbish",
    value4: "Cheater",
  },
  {
    _id: 4,
    color1: "Green",
    color2: "Any other color",
    founder: "Gellert Grindelwald,",
    headOfHouse: "Gilderoy Lockhart",
    houseGhost: "Hufflepuff",
    mascot: "Chameleon",
    name: "Chameleon",
    value1: "Nerdy",
    value2: "Teachers pet",
    value3: "Unimaginative",
    value4: "Plain",
  },
]
